spring:
  application:
    name: Expense_tracker
  data:
    mongodb:
      uri: mongodb+srv://charvibhake:2jjKeNUbF49AePX2@cluster0.ey1ambi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: expense_db
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: charvibhale@gmail.com
    password: wvww vjbx pmec dqdb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



server:
  port: 8080
  servlet:
    context-path: /expense
